version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.10.2
  - dependency-name: css-loader
    versions:
    - 5.2.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.15
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.4.1
  - dependency-name: webpack
    versions:
    - 5.24.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
